[package]
name = "everyondestroystheworld/stage-maker"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
react = "jsdotlua/react@17.1.0"
react-roblox = "jsdotlua/react-roblox@17.1.0"

[server-dependencies]
Stage = "christian-toney/edtw-stage@1.0.7"
Profile = "christian-toney/edtw-profile@1.0.2"